<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Phòng khám DEC</title>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta name="description" content="Creative CSS3 Animation Menus" />
        <meta name="keywords" content="menu, navigation, animation, transition, transform, rotate, css3, web design, component, icon, slide" />
        <meta name="author" content="Codrops" />
        <link rel="shortcut icon" href="../favicon.ico"> 
        <link rel="stylesheet" type="text/css" href="css/demo.css" />
        <link rel="stylesheet" type="text/css" href="css/style4.css" />
        <link href='http://fonts.googleapis.com/css?family=Terminal+Dosis' rel='stylesheet' type='text/css' />
        <link rel="stylesheet" type="text/css" href="css/normalize.css" />
        <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.2.0/css/font-awesome.min.css" />
        <link rel="stylesheet" type="text/css" href="css/menu_topside.css" />
    </head>
    <body>
        <div class="container">
            <div class="menu-wrap">
                <nav class="menu-top">
                    <div class="profile"><img src="img/user1.png" alt="Matthew Greenberg"/><span>Tên khách hàng</span></div>
                    <div class="icon-list">
                        <a href="#" data-toggle="tooltip" title="Cài đặt"><i class="fa fa-cog fa-fw"></i></a>
                        <a href="#" data-toggle="tooltip" title="Thông báo"><i class="fa fa-fw fa-bell-o"></i></a>
                        <a href="#" data-toggle="tooltip" title="Tin nhắn"><i class="fa fa-fw fa-envelope-o"></i></a>
                        <a href="#" data-toggle="tooltip" title="Đăng xuất"><i class="fa fa-sign-out"></i></a>
                    </div>
                </nav>
                <nav class="menu-side">
                    <a href="#">Thông tin 1</a>
                    <a href="#">Thông tin 2</a>
                    <a href="#">Thông tin 3</a>
                    <a href="#">Thông tin 4</a>
                </nav>
            </div>
            <button class="menu-button" data-toggle="tooltip" title="Menu" id="open-button"></button>
           
            <h1 style="border: 1px solid; padding: 10px;border-radius: 50px 50px; box-shadow: 5px 10px #888888; background: rgba(0,0,0,0.5);">Phòng khám DEC <span>Hân hạnh được phục vụ</span></h1>
            <div class="content">
                <ul class="ca-menu">
                    <li>
                        <a href="#">
                            <span class="ca-icon">F</span>
                            <div class="ca-content">
                                <h2 class="ca-main">Mua thuốc</h2>
                                <h3 class="ca-sub">Lựa chọn thuốc bạn cần</h3>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="ca-icon">H</span>
                            <div class="ca-content">
                                <h2 class="ca-main">Vị trí</h2>
                                <h3 class="ca-sub">Chọn nơi đến gần nhất</h3>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="ca-icon">N</span>
                            <div class="ca-content">
                                <h2 class="ca-main">Dịch vụ</h2>
                                <h3 class="ca-sub">Chăm sóc hiệu quả</h3>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="ca-icon">K</span>
                            <div class="ca-content">
                                <h2 class="ca-main">Đặt lịch</h2>
                                <h3 class="ca-sub">Tìm được thời gian phù hợp</h3>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="ca-icon">L</span>
                            <div class="ca-content">
                                <h2 class="ca-main">Hỗ trợ</h2>
                                <h3 class="ca-sub">Phục vụ 24/7</h3>
                            </div>
                        </a>
                    </li>
                </ul>
            </div><!-- content -->
        </div>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
                <script src="js/classie.js"></script>
        <script src="js/mainkh.js"></script>
    </body>
</html>