
    <!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://fonts.googleapis.com/css?family=Exo" rel="stylesheet">
		<!-- Favicon-->
		<link rel="shortcut icon" href="/giaodien/img/fav.png">
		<!-- Author Meta -->
		<meta name="author" content="Colorlib">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		<title>Phòng khám DEC</title>

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
			<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="/phongkham/css/linearicons.css">
			<link rel="stylesheet" href="/phongkham/css/font-awesome.min.css">
			<link rel="stylesheet" href="/phongkham/css/magnific-popup.css">
			<link rel="stylesheet" href="/phongkham/css/nice-select.css">
			<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
			<link rel="stylesheet" href="/phongkham/css/bootstrap.css">
			<link rel="stylesheet" href="/phongkham/css/main.css">
		</head>
		<body>
			<!-- Start Header Area -->
			<header class="default-header">
				<div class="container">
					<div class="header-wrap">
						<div class="header-top d-flex justify-content-between align-items-center">
							<div class="logo">
								<a href="/phongkham"><img src="/phongkham/img/logo.png" alt=""></a>
							</div>
							<div class="main-menubar d-flex align-items-center">
								<nav class="hide">
									<a href="/phongkham">Trang chủ</a>
									<a href="#service">Dịch vụ</a>
									<a href="#appoinment">Đặt lịch hẹn</a>
									<a href="#consultant">Chuyên gia tư vấn</a>
									<?php 
									if($this->session->has('id')){
							    		if($this->session->has('role')){
							    			$role = $this->session->get('role');
							    			if($role ===1){
							    			echo '<a href="dashboard">Menu</a>';
							    			}else{
							    				echo '<a href="dashboard/dashboard">Menu</a>';
							    			}
							    		}
							    	}else{
							    		echo '<a href="loginregis">Đăng nhập</a>';
							    	}
									?>

								</nav>
								<div class="menu-bar"><span class="lnr lnr-menu"></span></div>
							</div>
						</div>
					</div>
				</div>
			</header>
			<!-- End Header Area -->
    <?php echo $this->getContent() ?>  


			<!-- start footer Area -->
			<footer class="footer-area section-gap">
				<div class="container">
					<div class="row">
						<div class="col-lg-2  col-md-6">
							<div class="single-footer-widget">
								<h6 style="font-size: 18px;font-weight: 600;font-family: Open Sans, sans-serif;">Cài đặt</h6>
								<ul style="font-family: Exo, sans-serif;" class="footer-nav">
									<li><a href="#">Quản lý Website</a></li>
									<li><a href="#">Thiết lập</a></li>
									<li><a href="#">Phòng khám</a></li>
									<li><a href="#">Quảng bá</a></li>
								</ul>
							</div>
						</div>
						<div class="col-lg-4  col-md-6">
							<div class="single-footer-widget mail-chimp">
								<h6 style="font-size: 18px;font-weight: 600;font-family: Open Sans, sans-serif;" class="mb-20">Liên hệ chúng tôi</h6>
								<p style="font-family: Exo, sans-serif;">
									Số 10, Bàu Cát 1, Tân Bình, TP Hồ Chí Minh
								</p>
								<h3 style="font-family: Exo, sans-serif;">0-123-456-789</h3>
								<h3 style="font-family: Exo, sans-serif;">0-653-568-978</h3>
							</div>
						</div>
						<div class="col-lg-6  col-md-12">
							<div class="single-footer-widget newsletter">
								<h6 style="font-size: 18px;font-weight: 600;font-family: Open Sans, sans-serif;">Bản tin</h6>
								<p style="font-family: Exo, sans-serif;">Bạn có thể tin cậy chúng tôi. Chúng tôi chỉ gửi lời mời quảng cáo.</p>
								<div style="font-family: Exo, sans-serif;" id="mc_embed_signup">
									<form target="_blank" novalidate="true" action="" method="get" class="form-inline">

										<div class="form-group row" style="width: 100%">
											<div class="col-lg-8 col-md-12">
												<input name="EMAIL" placeholder="Gửi Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Nhập địa chỉ mail '" required="" type="email">
												<div style="position: absolute; left: -5000px;">
													<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
												</div>
											</div>

											<div class="col-lg-4 col-md-12">
												<button class="nw-btn primary-btn">Gửi<span class="lnr lnr-arrow-right"></span></button>
											</div>
										</div>
										<div class="info"></div>
									</form>
								</div>
							</div>
						</div>
					</div>

					<div class="row footer-bottom d-flex justify-content-between">
						<p class="col-lg-8 col-sm-12 footer-text m-0">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							Bản quyền &copy;<script>document.write(new Date().getFullYear());</script> Giao diện | DEC <i class="fa fa-heart-o" aria-hidden="true"></i> Bởi <a href="" target="_blank">Công ty DEC</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
						<div class="col-lg-4 col-sm-12 footer-social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</footer>
			<!-- End footer Area -->

			<script src="/phongkham/js/vendor/jquery-2.2.4.min.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
			<script src="/phongkham/js/vendor/bootstrap.min.js"></script>
			<script src="/phongkham/js/jquery.ajaxchimp.min.js"></script>
			<script src="/phongkham/js/jquery.nice-select.min.js"></script>
			<script src="/phongkham/js/jquery.sticky.js"></script>
			<script src="/phongkham/js/parallax.min.js"></script>
			<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
			<script src="/phongkham/js/jquery.magnific-popup.min.js"></script>
			<script src="/phongkham/js/waypoints.min.js"></script>
			<script src="/phongkham/js/jquery.counterup.min.js"></script>
			<script src="/phongkham/js/main.js"></script>
		</body>
	</html>
